language: node_js
node_js:
  - "node"
  - "8"
  - "7"
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
    - "node_modules"
script:
  - npm test
after_success:
  - codecov
deploy:
  provider: npm
  skip_cleanup: true
  on:
    branch: master
    node: "node"
    tags: true
